Add bulk insert/update feature
IBM-Swift/Kitura-CouchDB pull request #63
Opened 2017-08-09 14:20 UTC by iuliancorcoja

## Description

Added a new method to database to modify multiple documents with a single request.

## Motivation and Context

I need to remove or update multiple documents at once by providing a list of JSON objects containing `_id` and `_rev`.

## How Has This Been Tested?

I tested this feature on my machine with macOS Sierra and CouchDB installed as well as on Bluemix platform with an app using IBM Cloudant service.

## Checklist:

- [x] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [ ] If applicable, I have updated the documentation accordingly.
- [ ] If applicable, I have added tests to cover my changes.

2017-08-10 19:43 UTC, na-gupta commented
@iuliancorcoja Thank you for this PR. It looks good to me. Could you please add a unit test for the new function?

2017-08-10 19:45 UTC, na-gupta commented
The travis build will fail because of an issue accessing credentials by users outside the org. So don't be concerned about the build failing.

2017-08-24 22:26 UTC, iuliancorcoja commented
@na-gupta, I've added 3 unit tests for bulk insert, update and delete. Please let me know if there is anything else needed.

Regards,
Iulian.

2017-08-30 15:42 UTC, na-gupta requested changes
@iuliancorcoja  Looks great. Just a couple of small changes needed to the tests:
- Please add DocumentBulkUpdateTests to Tests/LinuxMain.swift so they run on Linux builds as well.
- Please set dbSecuredConnection to false. Our testing cloudant instance is not setup for https connections.

2017-08-30 15:42 UTC, na-gupta commented on Tests/CouchDBTests/DocumentBulkUpdateTests.swift
> +	static let dbSecuredConnection = true
Please set `dbSecuredConnection` to false. Our testing cloudant instance is not setup for https connections.

2017-08-30 21:40 UTC, iuliancorcoja commented
@na-gupta, done!

2017-08-31 02:04 UTC, na-gupta approved these changes

2017-08-31 02:05 UTC, merged

2017-08-31 02:57 UTC, na-gupta commented
@iuliancorcoja Merged and tagged (1.7.1). Thank you!