Porting to KituraNIO
IBM-Swift/Kitura-CouchDB pull request #80
Opened 2018-07-25 00:49 UTC by saiHemak

## Description

## Motivation and Context

## How Has This Been Tested?

## Checklist:

- [ ] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [ ] If applicable, I have updated the documentation accordingly.
- [ ] If applicable, I have added tests to cover my changes.

2018-07-25 01:47 UTC, saiHemak commented
@djones6 KituraNIO uses CNIOOpenSSL library which is dependent upon a lib-ressl native library .XCode requires lib-ressl library to be update for Kitura-NIO .Looks like the failure is due to the same. I am not sure how can I do that in Travis environment .Can you please help me out on the same.

2018-07-26 09:40 UTC, saiHemak commented
@djones6  please review

2018-08-16 11:08 UTC, saiHemak commented
@djones6  Please review

2018-08-28 10:37 UTC, djones6 requested changes

2018-08-28 10:37 UTC, djones6 commented on Package.swift
> +            dependencies: ["HeliumLogger", "KituraNIO", "SwiftyJSON"]),
This will need to be `KituraNet` now that https://github.com/IBM-Swift/Kitura-NIO/pull/72 has been merged.

2018-08-28 10:37 UTC, djones6 commented on Package.swift
> +        .package(url: "https://github.com/IBM-Swift/Kitura-NIO.git", from: "0.0.0"),
I think this now needs to be `from: "1.0.0"` as Kitura-NIO has recently been tagged at that major

2018-08-28 10:37 UTC, djones6 commented on Sources/CouchDB/CouchDBClient.swift
> +import KituraNIO
All these changes should now be unnecessary (due to https://github.com/IBM-Swift/Kitura-NIO/pull/72)

2018-08-28 13:58 UTC, djones6 requested changes
Thinking more about this, should we be using the `KITURA_NIO` env var trick (as per https://github.com/IBM-Swift/Kitura/pull/1324) to choose which package to depend on?

I think we'd need to do so in order for someone to have a project that depends on both Kitura and Kitura-CouchDB which can be compiled on either Net or NIO.

2018-08-28 14:05 UTC, saiHemak commented
@djones6  I agree.. I am done with changes and waiting for merge  of https://github.com/IBM-Swift/Kitura/pull/1324 .

2018-08-31 06:27 UTC, closed without merging