Allow users to switch to using KituraNIO
IBM-Swift/Kitura-CouchDB pull request #83
Opened 2018-10-11 09:24 UTC by mamabusi

2018-10-11 12:37 UTC, djones6 requested changes
The .travis.yml needs sorting out...

2018-10-11 12:37 UTC, djones6 commented on .travis.yml
> +      env: SWIFT_SNAPSHOT=swift-4.2-DEVELOPMENT-SNAPSHOT-2018-06-19-a TESTDB_NAME=testdb_3
This should just be '4.2'

2018-10-11 12:37 UTC, djones6 commented on .travis.yml
> +      env: SWIFT_SNAPSHOT=swift-4.2-DEVELOPMENT-SNAPSHOT-2018-06-19-a KITURA_NIO=1 TESTDB_NAME=testdb_4
This should just be '4.2'

2018-10-11 12:37 UTC, djones6 commented on .travis.yml
> +      env: SWIFT_SNAPSHOT=4.2 KITURA_NIO TESTDB_NAME=testdb_10
This looks like a typo - should be `KITURA_NIO=1`

2018-10-11 12:37 UTC, djones6 commented on .travis.yml
> +      env: SWIFT_SNAPSHOT=swift-4.2-DEVELOPMENT-SNAPSHOT-2018-06-04-a KITURA_NIO=1 TESTDB_NAME=testdb_8
These two are redundant as xcode10 + 4.2 (release build) are included below

2018-10-11 13:29 UTC, mamabusi commented
@djones6 Thanks for the review. Have addressed the changes requested.

2018-10-12 08:55 UTC, djones6 approved these changes

2018-10-12 09:47 UTC, ianpartridge approved these changes

2018-10-12 09:53 UTC, merged