WIP: Replace SwiftyJSON with Codable
IBM-Swift/Kitura-CouchDB pull request #86
Opened 2018-11-07 15:19 UTC by Andrew-Lees11

## Description
This pull requests removed the CouchDB dependency on SwiftyJSON. 

The API's to interact with the database have been replaced to use Codable objects. As such this is a breaking change. 

## Motivation and Context

This was requested to add type safety to the CouchDB API and was requested in issue #73.
This change removes the need to cast the response JSON to and from swift types. Instead you can just store and retrieve Codable objects.

## How Has This Been Tested?
The current tests have been updated to use the new API and were all passing when running locally.

## Checklist:
- [x] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [ ] If applicable, I have updated the documentation accordingly.
- [x] If applicable, I have added tests to cover my changes.

2019-01-08 13:48 UTC, kilnerm requested changes
Mostly grammar police and white space gripes.

Would be good if we can guard against overflowing the Int16 cast!

2019-01-08 13:48 UTC, kilnerm commented on Sources/CouchDB/CouchDBClient.swift
> +    ///     - callback: Callback containing the newly created `Database`, or an `CouchDBError` on failure.
This should be ", or a `CouchDBError`..."

2019-01-08 13:48 UTC, kilnerm commented on Sources/CouchDB/CouchDBClient.swift
> +    ///     - callback: Callback containing the result of the lookup or an CouchDBError if one occurred.
This should be "....or a CouchDBError..."

2019-01-08 13:48 UTC, kilnerm commented on Sources/CouchDB/CouchDBClient.swift
> +    ///     - callback: Callback containing an CouchDBError if one occurred.
This should be "....containing a CouchDBError..."

2019-01-08 13:48 UTC, kilnerm commented on Sources/CouchDB/CouchDBClient.swift
> +    ///     - callback: Callback containing an CouchDBError if one occurred.
This should be "....containing a CouchDBError..."

2019-01-08 13:48 UTC, kilnerm commented on Sources/CouchDB/CouchDBClient.swift
> +    ///     - callback: Callback containing an array of UUIDs or an CouchDBError if one occured.
This should be "....or a CouchDBError..."

2019-01-08 13:48 UTC, kilnerm commented on Sources/CouchDB/CouchDBClient.swift
> +    /// - parameter callback: Callback containing the UUID or an CouchDBError if one occurred.
This should be "....or a CouchDBError..."

2019-01-08 13:48 UTC, kilnerm commented on Sources/CouchDB/ConnectionProperties.swift
> +    public init(host: String, port: Int, secured: Bool, username: String?=nil, password: String?=nil) {
Given port is later cast to Int16 could we update the doc here to indicate a maximum value, or perhaps even prevent it being set above the max value?

2019-01-08 13:48 UTC, kilnerm commented on Sources/CouchDB/CouchDBUtils.swift
> +            var error = try JSONDecoder().decode(CouchDBError.self, from: body)
A comment here explaining that error will be of type CouchDBError would be useful. I had to go look up JSONDecoder to work this out.

2019-01-08 13:48 UTC, kilnerm commented on Sources/CouchDB/Database.swift
> +
Would be good to clean up these white space changes.

2019-01-08 13:48 UTC, kilnerm commented on Sources/CouchDB/Database.swift
> +
White space.

2019-01-08 13:48 UTC, kilnerm commented on Sources/CouchDB/Database.swift
> +    ///     - callback: Callback containing either the `AllDatabaseDocuments` or an CouchDBError.
This should be "....or a CouchDBError..."

2019-01-08 13:48 UTC, kilnerm commented on Sources/CouchDB/Database.swift
> +    ///     - callback: Callback containing the `DocumentResponse` or an CouchDBError.
This should be "....or a CouchDBError..."

2019-01-08 13:48 UTC, kilnerm commented on Sources/CouchDB/Database.swift
> +    ///     - callback: Callback containing the `DocumentResponse` or an CouchDBError.
This should be "....or a CouchDBError..."

2019-01-08 13:48 UTC, kilnerm commented on Sources/CouchDB/Database.swift
> +    ///     - callback: Callback containing either the retrieved attachment data and the content type of the attachment or an CouchDBError.
This should be "....or a CouchDBError..."

2019-01-08 13:48 UTC, kilnerm commented on Sources/CouchDB/Database.swift
> +    ///     - failOnNotFound: Bool indicating whether to return an CouchDBError if the attachment could not be found.
Wasn't this flag removed?

2019-01-08 13:48 UTC, kilnerm commented on Sources/CouchDB/Database.swift
> +    ///     - callback: Callback containing either the `DocumentResponse` or an CouchDBError.
This should be "....or a CouchDBError..."

2019-01-08 13:48 UTC, kilnerm commented on Tests/CouchDBTests/Utils.swift
> +
White space

2019-01-11 11:58 UTC, helenmasters commented on README.md
> +The `_rev` field is the revision of the document. It is returned when you make requests and is used to prevent conflicts from multiple users updating the same document.
Andy, can you bullet point or similar the definitions for _id field and _rev field (or put them in a separate paragraph)?

2019-01-11 12:44 UTC, kilnerm commented on Sources/CouchDB/CouchDBUtils.swift
> +            var error = try JSONDecoder().decode(CouchDBError.self, from: body)
Actually, ignore this!

2019-01-11 12:44 UTC, kilnerm approved these changes

2019-01-11 13:12 UTC, helenmasters approved these changes
Approving as only 3 minor comments to be addressed.

2019-01-11 13:12 UTC, helenmasters commented on Sources/CouchDB/CouchErrorResponse.swift
> +    /// The error that occured.
occurred not occured

2019-01-11 13:12 UTC, helenmasters commented on Sources/CouchDB/CouchErrorResponse.swift
> +    // Don't decode statusCode, It is extracted from the HTTP request.
It should have a lowercase i after the comma

2019-01-11 13:12 UTC, helenmasters commented on Sources/CouchDBSample/main.swift
>  // Create couchDBClient instance using conn properties
conn properties should be either connProperties or probably better "connection properties" in this comment.

2019-01-28 11:47 UTC, merged